# Generated by Django 4.1.2 on 2022-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilar',
            name='yazi_firstletter',
            field=models.CharField(default='', max_length=50),
        ),
    ]
