# Generated by Django 4.1.2 on 2022-10-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_yazilar_yazi_firstletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazilar',
            name='yazi_firstletter',
        ),
    ]
